version: '3.7'

networks:
  redis-network:
    driver: bridge

services:
  redis-master:
    image: 'redis:7.2'
    container_name: redis-master
    volumes:
      - ./redis-master.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - redis-network

  redis-slave1:
    image: 'redis:7.2'
    container_name: redis-slave1
    depends_on:
      - redis-master
    volumes:
      - ./redis-slave.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - redis-network

  redis-slave2:
    image: 'redis:7.2'
    container_name: redis-slave2
    depends_on:
      - redis-master
    volumes:
      - ./redis-slave.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - redis-network

  redis-sentinel1:
    image: 'redis:7.2'
    container_name: redis-sentinel1
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    volumes:
      - ./redis-sentinel.conf:/usr/local/etc/redis/redis-sentinel.conf
    command: [ "redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf" ]
    networks:
      - redis-network

  redis-sentinel2:
    image: 'redis:7.2'
    container_name: redis-sentinel2
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    volumes:
      - ./redis-sentinel.conf:/usr/local/etc/redis/redis-sentinel.conf
    command: [ "redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf" ]
    networks:
      - redis-network

  redis-sentinel3:
    image: 'redis:7.2'
    container_name: redis-sentinel3
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    volumes:
      - ./redis-sentinel.conf:/usr/local/etc/redis/redis-sentinel.conf
    command: [ "redis-sentinel", "/usr/local/etc/redis/redis-sentinel.conf" ]
    networks:
      - redis-network
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=redis-master:redis-master:6379:0:str0ng_passw0rd,redis-slave1:redis-slave1:6379:0:str0ng_passw0rd,redis-slave2:redis-slave2:6379:0:str0ng_passw0rd
      - SENTINELS=redis-sentinel1:26379,redis-sentinel2:26379,redis-sentinel3:26379
      - REDIS_PASSWORD=str0ng_passw0rd
    depends_on:
      - redis-sentinel1
      - redis-sentinel2
      - redis-sentinel3
    ports:
      - "8088:8081"
    networks:
      - redis-network
